data_timesteps: 1
data_presentation_pattern: [1]

mounted_datasets:
    - imagenet

class_index_files:
    imagenet: imagenet_class_index.json
    imagenette: imagenet_class_index.json
    tinyimagenet: tinyimagenet_class_index.json

# used for setup the ffcv dataloader
data_resolution:
    mnist: 28
    cifar10: 32
    cifar100: 32
    tinyimagenet: 64
    imagenet: 224
    snakenet: 224
    imagenette: 224

# data statistics for normalization
data_statistics:
    mnist:
        mean: [0.1307]
        std: [0.3081]
    cifar10:
        mean: [0.5071, 0.4867, 0.4408]
        std: [0.2675, 0.2565, 0.2761]
    cifar100:
        mean: [0.5071, 0.4867, 0.4408]
        std: [0.2675, 0.2565, 0.2761]
    imagenet:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
    imagenette:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
    tinyimagenet:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]

# predefined data subgroups for testing
# selected via wildcards in filenames "*_{data_name}_{status}_{data_group}"
data_groups:
    mnist:
        '01':
            - 0
            - 1
        '38':
            - 3
            - 8
        '89':
            - 8
            - 9
    tinyimagenet:
        mollusks:
            - 13 # jellyfish
            - 14 # brain_coral
            - 15 # snail
            - 16 # slug
            - 17 # sea_slug
            - 18 # American_lobster
            - 19 # spiny_lobster
            - 46 # sea cucumber
        catdogs:
            - 187 # Yorkshire_terrier
            - 207 # Golden_retriever
            - 208 # Labrador_retriever
            - 235 # German_shepherd
            - 267 # standard_poodle
            - 281 # tabby
            - 283 # Persian_cat
            - 285 # Egyptian_cat
            - 286 # cougar
            - 291 # lion
    imagenet:
        imagenette:
            - 0 # tench
            - 217 # English springer
            - 482 # cassette player
            - 491 # chain saw
            - 497 # church
            - 566 # French horn
            - 569 # garbage truck
            - 571 # gas pump
            - 574 # golf ball
            - 701 # parachute
        snakes:
            - 54  # hognose_snake
            - 60  # night_snake
            - 62  # rock_python
            - 66  # horned_viper
            - 67  # diamondback
            - 68  # sidewinder
        insects:
            - 304 # leaf beetle
            - 310 # ant
            - 311 # grasshopper
            - 312 # cricket
            - 313 # walking stick
            - 314 # cockroach
            - 315 # mantis
            - 316 # cicada
            - 317 # leafhopper
            - 318 # lacewing
            - 319 # dragonfly
        one:
            - 0 # tench
    imagenette:
        one:
            - 0 # tench
    snakenet:
        cool:
            - 1  # night_snake
            - 2  # rock_python
            - 4  # diamondback
    cifar100:
        invertebrates:
            - 6  # bee
            - 7  # beetle
            - 14 # butterfly
            - 18 # caterpillar
            - 24 # cockroach
            - 26 # crab
            - 45 # lobster
            - 77 # snail
            - 79 # spider
            - 99 # worm
        alphabet:
            - 0  # apple
            - 8  # bicycle
            - 18 # caterpillar
            - 29 # dinosaur
            - 31 # elephant
            - 33 # forest
            - 35 # girl
            - 37 # house
            - 38 # kangaroo
            - 44 # lizard
            - 51 # mushroom
            - 53 # orange
            - 63 # porcupine
            - 69 # rocket
            - 82 # sunflower
