experiment_config:

  categories:
    rctype: ['depthpointwise', 'pointdepthwise', 'self', 'full', 'local', 'localdepthwise']
    rctarget: ['output', 'input', 'middle']  # Target for recurrent connections
    pattern: ['01110', '11100', '1']
    dsteps: [20]
    tsteps: [5, 10, 15, 20]
    dt: [2]
    tau: [3, 5, 9]
    tff: [0, 10]
    trc: [2, 6, 10]
    tsk: [0, 4, 8]
    # lossrt: [0, 4, 8, 20, 38]
    lossrt: [0, 6, 12, 18]
    idle: [0, 1, 5, 10, 15]
    feedback: ['add','false', 'mul']
    skip: ['true', 'false']
    dloader: ['ffcv', 'torch']
    ffonly: ['true', 'false']
    
  response:
    status: trained
    parameter: stim
    data_loader: StimulusDuration
    data_args:
      dsteps: 60
      intro: 1
      stim: [30]
      idle: [20]

  responseffonly:
    status: trained
    parameter: ffonly
    data_loader: StimulusDuration
    data_args:
      dsteps: 4
      intro: 0
      stim: 2
      ffonly: ['true', 'false']

  stability:
    status: trained
    parameter: stim
    data_loader: StimulusDuration
    data_args:
      dsteps: 125
      stim: [25, 100]
      intro: 0
      idle: [20]

  adaption:
    status: trained
    parameter: inadapt
    data_loader: StimulusDuration
    data_args:
      dsteps: 40
      intro: 1
      stim: [20]
      idle: [20]
      inadapt: [0, 0.95, 0.9, 0.8, 0.7]

  nullcondition:
    status: trained
    parameter: stim
    data_loader: StimulusDuration
    data_args:
      dsteps: 200
      intro: 95
      stim: [10]

  idleresponse:
    status: trained
    parameter: idle
    data_loader: StimulusDuration
    data_args:
      dsteps: 50
      intro: 0
      stim: [25]
      idle: [0, 1, 5, 10, 15]

  duration:
    status: trained
    parameter: stim
    data_loader: StimulusDuration
    data_args:
      dsteps: 30
      intro: 1
      stim: [1, 3, 5, 10, 20]
      idle: 20

  contrast:
    status: trained
    parameter: contrast
    data_loader: StimulusContrast
    data_args:
      dsteps: 30
      intro: 1
      stim: 20
      contrast: [0.1, 0.3, 0.5, 0.7, 0.9]
      idle: 20

  interval:
    status: trained
    parameter: interval
    data_loader: StimulusInterval
    data_args:
      dsteps: 40
      intro: 1
      stim: 6
      interval: [1, 2, 4, 8, 16]
      idle: 20

  uniformnoise:
    status: trained
    parameter: ssnr
    data_loader: StimulusNoise
    data_args:
      dsteps: 20
      noisetype: uniform
      ssnr: [0.0, 0.1, 0.3, 0.4, 0.5, 0.6, 0.7, 0.9, 1.0]
      tempmode: 'dynamic'
      idle: 20

  uniformnoiseffonly:
    status: trained
    parameter: ssnr
    data_loader: StimulusNoise
    data_args:
      dsteps: 20
      noisetype: uniform
      ssnr: [0.0, 0.1, 0.3, 0.4, 0.5, 0.6, 0.7, 0.9, 1.0]
      tempmode: 'dynamic'
      idle: 20
      ffonly: 'true'

  uniformnoiseiid:
    status: trained
    parameter: noiselevel
    data_loader: StimulusNoise
    data_args:
      dsteps: 20
      noisetype: uniform
      ssnr: [0.0, 0.1, 0.3, 0.4, 0.5, 0.6, 0.7, 0.9, 1.0]
      tempmode: 'dynamic'
      idle: 20

  saltpeppernoise:
    status: trained
    parameter: noiselevel
    data_loader: StimulusNoise
    data_args:
      dsteps: 20
      noisetype: saltpepper
      ssnr: [0.0, 0.1, 0.3, 0.4, 0.5, 0.6, 0.7, 0.9, 1.0]
      tempmode: 'static'
      idle: 20

  saltpeppernoiseiid:
    status: trained
    parameter: noiselevel
    data_loader: StimulusNoise
    data_args:
      dsteps: 20
      noisetype: saltpepper
      noiselevel: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5]
      tempmode: 'dynamic'
      idle: 20

  poissonnoise:
    status: trained
    parameter: ssnr
    data_loader: StimulusNoise
    data_args:
      dsteps: 20
      noisetype: poisson
      ssnr: [0.0, 0.1, 0.3, 0.4, 0.5, 0.6, 0.7, 0.9, 1.0]
      tempmode: 'dynamic'
      idle: 20

  poissonnoiseffonly:
    status: trained
    parameter: ssnr
    data_loader: StimulusNoise
    data_args:
      dsteps: 20
      noisetype: poisson
      ssnr: [0.0, 0.1, 0.3, 0.4, 0.5, 0.6, 0.7, 0.9, 1.0]
      tempmode: 'dynamic'
      idle: 20
      ffonly: 'true'

  poissonnoiseiid:
    status: trained
    parameter: noiselevel
    data_loader: StimulusNoise
    data_args:
      dsteps: 20
      noisetype: poisson
      noiselevel: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5]
      tempmode: 'dynamic'
      idle: 20

  poissonnoiseiidffonly:
    status: trained
    parameter: ffonly
    data_loader: StimulusNoise
    data_args:
      dsteps: 20
      noisetype: poisson
      noiselevel: [0.3]
      tempmode: 'dynamic'
      idle: 20
      ffonly: ['true', 'false']

  gaussiannoise:
    status: trained
    parameter: ssnr
    data_loader: StimulusNoise
    data_args:
      dsteps: 20
      noisetype: gaussian
      ssnr: [0.0, 0.1, 0.3, 0.4, 0.5, 0.6, 0.7, 0.9, 1.0]
      # tempmode: 'dynamic'
      idle: 20

  gaussiancorrnoise:
    status: trained
    parameter: ssnr
    data_loader: StimulusNoise
    data_args:
      dsteps: 20
      noisetype: gaussian
      spatialcorr: 'true'
      ssnr: [0.0, 0.1, 0.3, 0.4, 0.5, 0.6, 0.7, 0.9, 1.0]
      # tempmode: 'dynamic'
      idle: 20

  phasescramblednoise:
    status: trained
    parameter: ssnr
    data_loader: StimulusNoise
    data_args:
      dsteps: 20
      noisetype: phasescrambled
      ssnr: [0.0, 0.1, 0.3, 0.4, 0.5, 0.6, 0.7, 0.9, 1.0]
      # tempmode: 'dynamic'
      idle: 20

  gaussiannoiseffonly:
    status: trained
    parameter: ssnr
    data_loader: StimulusNoise
    data_args:
      dsteps: 20
      noisetype: gaussian
      ssnr: [0.0, 0.1, 0.3, 0.4, 0.5, 0.6, 0.7, 0.9, 1.0]
      # tempmode: 'dynamic'
      idle: 20
      ffonly: 'true'

  gaussiancorrnoiseffonly:
    status: trained
    parameter: ssnr
    data_loader: StimulusNoise
    data_args:
      dsteps: 20
      noisetype: gaussian
      spatialcorr: 'true'
      ssnr: [0.0, 0.1, 0.3, 0.4, 0.5, 0.6, 0.7, 0.9, 1.0]
      # tempmode: 'dynamic'
      idle: 20
      ffonly: 'true'

  phasescramblednoiseffonly:
    status: trained
    parameter: ssnr
    data_loader: StimulusNoise
    data_args:
      dsteps: 20
      noisetype: phasescrambled
      ssnr: [0.0, 0.1, 0.3, 0.4, 0.5, 0.6, 0.7, 0.9, 1.0]
      # tempmode: 'dynamic'
      idle: 20
      ffonly: 'true'

  noise:
    parameter: ssnr