experiment_config:

  categories:
    rctype: ['depthpointwise', 'pointdepthwise', 'self', 'full', 'local', 'localdepthwise']
    rctarget: ['output', 'input', 'middle']  # Target for recurrent connections
    pattern: ['01110', '11100', '1']
    dsteps: [20]
    dt: [2]
    tau: [3, 9, 15]
    tff: [0, 10]
    trc: [2, 6, 10]
    tsk: [0, 4, 8]
    lossrt: [0, 5, 10, 15, 19]
    feedback: ['add','false', 'mul']
    
  response:
    status: trained
    parameter: stim
    data_loader: StimulusDuration
    data_args:
      dsteps: 50
      intro: 0
      stim: [30]

  responseffonly:
    status: trained
    parameter: stim
    data_loader: StimulusDuration
    data_args:
      dsteps: 50
      intro: 0
      stim: [30]
      ffonly: true

  stability:
    status: trained
    parameter: stim
    data_loader: StimulusDuration
    data_args:
      dsteps: 200
      stim: [100]

  duration:
    status: trained
    parameter: stim
    data_loader: StimulusDuration
    data_args:
      dsteps: 50
      intro: 0
      stim: [1,2,4,6,10,20]

  contrast:
    status: trained
    parameter: contrast
    data_loader: StimulusContrast
    data_args:
      dsteps: 50
      intro: 0
      stim: 30
      contrast: [0.1, 0.2, 0.4, 0.6, 0.8, 1.0]  

  interval:
    status: trained
    parameter: interval
    data_loader: StimulusInterval
    data_args:
      dsteps: 50
      intro: 0
      stim: 6
      interval: [1, 2, 4, 8, 16]
