experiment_config:

  categories:
    rctype: ['depthpointwise', 'pointdepthwise', 'self', 'full', 'local', 'localdepthwise']
    rctarget: ['output', 'input', 'middle']  # Target for recurrent connections
    pattern: ['1011', '1']
    dsteps: [1, 20]
    tsteps: [8, 14, 20, 26]
    dt: [2]
    tau: [3, 5, 9]
    tff: [0, 10]
    trc: [2, 6, 10]
    tsk: [0, 4, 8]
    # lossrt: [0, 4, 8, 20, 38]  # for pattern=1
    lossrt: [0, 4, 8, 18, 28]  # for pattern=1011 + shuffle
    idle: [0, 1, 5, 10, 20]
    feedback: ['add','false', 'mul']
    skip: ['true', 'false']
    dloader: ['ffcv', 'torch']
    ffonly: ['true', 'false']
    pretrained: ['true', 'false']
    energyloss: [0, 0.1, 0.2, 0.3, 0.5] #, 1.0, 2.0] #0.3
    # energyloss: [0, 0.1, 0.3, 0.5, 1.0] #0.3
    
  response:
    parameter: stim
    data_loader: StimulusDuration
    data_args:
      dsteps: 60
      intro: 1
      stim: [30]
      idle: [20]

  responseffonly:
    parameter: ffonly
    data_loader: StimulusDuration
    data_args:
      dsteps: 4
      intro: 0
      stim: 2
      ffonly: ['true', 'false']

  responseintermediate:
    status: [trained-epoch=49, trained-epoch=99, trained-epoch=149, trained-epoch=199, trained-epoch=249, trained-epoch=299, trained-epoch=349]
    parameter: stim
    data_loader: StimulusDuration
    data_args:
      dsteps: 60
      intro: 1
      stim: [30]
      idle: [20]

  stabilityintermediate:
    status: [trained-epoch=199, trained-epoch=249, trained-epoch=299, trained-epoch=349]
    parameter: stim
    data_loader: StimulusDuration
    data_args:
      dsteps: 125
      intro: 1
      stim: [100]
      idle: [20]

  stability:
    parameter: stim
    data_loader: StimulusDuration
    data_args:
      dsteps: 125
      # stim: [25, 100]
      stim: [100]
      intro: 0
      idle: [20]

  adaption:
    parameter: inadapt
    data_loader: StimulusDuration
    data_args:
      dsteps: 40
      intro: 1
      stim: [20]
      idle: [20]
      inadapt: [0, 0.95, 0.9, 0.8, 0.7]

  nullcondition:
    parameter: stim
    data_loader: StimulusDuration
    data_args:
      dsteps: 200
      intro: 95
      stim: [10]

  idleresponse:
    parameter: idle
    data_loader: StimulusDuration
    data_args:
      dsteps: 50
      intro: 0
      stim: [25]
      # idle: [0, 1, 5, 10, 15, 100]
      idle: [100]

  duration:
    parameter: stim
    data_loader: StimulusDuration
    data_args:
      dsteps: 30
      intro: 1
      stim: [1, 3, 5, 10, 20]
      idle: 20

  contrast:
    parameter: contrast
    data_loader: StimulusContrast
    data_args:
      dsteps: 30
      intro: 1
      stim: 20
      contrast: [0.1, 0.3, 0.5, 0.7, 0.9]
      idle: 20

  interval:
    parameter: interval
    data_loader: StimulusInterval
    data_args:
      dsteps: 40
      intro: 1
      stim: 6
      interval: [1, 2, 4, 8, 16]
      idle: 20

  uniformnoise:
    parameter: ssnr
    data_loader: StimulusNoise
    data_args:
      dsteps: 20
      noisetype: uniform
      ssnr: [0.2, 0.4, 0.6, 0.8, 1.0]
      tempmode: 'dynamic'
      idle: 20

  uniformnoiseffonly:
    parameter: ssnr
    data_loader: StimulusNoise
    data_args:
      dsteps: 20
      noisetype: uniform
      ssnr: [0.2, 0.4, 0.6, 0.8, 1.0]
      tempmode: 'dynamic'
      idle: 20
      ffonly: 'true'

  uniformnoiseiid:
    parameter: noiselevel
    data_loader: StimulusNoise
    data_args:
      dsteps: 20
      noisetype: uniform
      ssnr: [0.2, 0.4, 0.6, 0.8, 1.0]
      tempmode: 'dynamic'
      idle: 20

  saltpeppernoise:
    parameter: noiselevel
    data_loader: StimulusNoise
    data_args:
      dsteps: 20
      noisetype: saltpepper
      ssnr: [0.2, 0.4, 0.6, 0.8, 1.0]
      tempmode: 'static'
      idle: 20

  saltpeppernoiseiid:
    parameter: noiselevel
    data_loader: StimulusNoise
    data_args:
      dsteps: 20
      noisetype: saltpepper
      ssnr: [0.2, 0.4, 0.6, 0.8, 1.0]
      tempmode: 'dynamic'
      idle: 20

  poissonnoise:
    parameter: ssnr
    data_loader: StimulusNoise
    data_args:
      dsteps: 20
      noisetype: poisson
      ssnr: [0.2, 0.4, 0.6, 0.8, 1.0]
      tempmode: 'dynamic'
      idle: 20

  poissonnoiseffonly:
    parameter: ssnr
    data_loader: StimulusNoise
    data_args:
      dsteps: 20
      noisetype: poisson
      ssnr: [0.2, 0.4, 0.6, 0.8, 1.0]
      tempmode: 'dynamic'
      idle: 20
      ffonly: 'true'

  poissonnoiseiid:
    parameter: noiselevel
    data_loader: StimulusNoise
    data_args:
      dsteps: 20
      noisetype: poisson
      ssnr: [0.2, 0.4, 0.6, 0.8, 1.0]
      tempmode: 'dynamic'
      idle: 20

  poissonnoiseiidffonly:
    parameter: ffonly
    data_loader: StimulusNoise
    data_args:
      dsteps: 20
      noisetype: poisson
      noiselevel: [0.3]
      tempmode: 'dynamic'
      idle: 20
      ffonly: ['true', 'false']

  gaussiannoise:
    parameter: ssnr
    data_loader: StimulusNoise
    data_args:
      dsteps: 20
      noisetype: gaussian
      ssnr: [0.2, 0.4, 0.6, 0.8, 1.0]
      # tempmode: 'dynamic'
      idle: 20

  gaussiancorrnoise:
    parameter: ssnr
    data_loader: StimulusNoise
    data_args:
      dsteps: 20
      noisetype: gaussian
      spatialcorr: 'true'
      ssnr: [0.2, 0.4, 0.6, 0.8, 1.0]
      # tempmode: 'dynamic'
      idle: 20

  phasescramblednoise:
    parameter: ssnr
    data_loader: StimulusNoise
    data_args:
      dsteps: 20
      noisetype: phasescrambled
      ssnr: [0.2, 0.4, 0.6, 0.8, 1.0]
      # tempmode: 'dynamic'
      idle: 20

  gaussiannoiseffonly:
    parameter: ssnr
    data_loader: StimulusNoise
    data_args:
      dsteps: 20
      noisetype: gaussian
      ssnr: [0.2, 0.4, 0.6, 0.8, 1.0]
      # tempmode: 'dynamic'
      idle: 20
      ffonly: 'true'

  gaussiancorrnoiseffonly:
    parameter: ssnr
    data_loader: StimulusNoise
    data_args:
      dsteps: 20
      noisetype: gaussian
      spatialcorr: 'true'
      ssnr: [0.2, 0.4, 0.6, 0.8, 1.0]
      # tempmode: 'dynamic'
      idle: 20
      ffonly: 'true'

  phasescramblednoiseffonly:
    parameter: ssnr
    data_loader: StimulusNoise
    data_args:
      dsteps: 20
      noisetype: phasescrambled
      ssnr: [0.2, 0.4, 0.6, 0.8, 1.0]
      # tempmode: 'dynamic'
      idle: 20
      ffonly: 'true'

  noise:
    parameter: ssnr

  hundred:
    parameter: stim
    data_loader: StimulusDuration
    data_args:
      dsteps: 100
      stim: 100
      intro: 0
      idle: 100